---
- name: Zypper - Install Alloy from remote URL
  community.general.zypper:
    name: "{{ alloy_download_url_rpm }}"
    state: present
    disable_gpg_check: true
  notify: restart alloy
  when: __current_deployed_version.stdout is not defined or alloy_version not in __current_deployed_version.stdout
