---
# defaults file for mimir
mimir_version: "latest"
mimir_uninstall: false
__mimir_arch: "{{ arch_mapping[ansible_facts['architecture']] | default('amd64') }}"
mimir_download_url_rpm: "https://github.com/grafana/mimir/releases/download/mimir-{{ mimir_version }}/mimir-{{ mimir_version }}_{{ __mimir_arch }}.rpm"
mimir_download_url_deb: "https://github.com/grafana/mimir/releases/download/mimir-{{ mimir_version }}/mimir-{{ mimir_version }}_{{ __mimir_arch }}.deb"
mimir_working_path: "/var/lib/mimir"
mimir_ruler_alert_path: "{{ mimir_working_path }}/ruler"
mimir_http_listen_port: 8080
mimir_http_listen_address: "0.0.0.0"

arch_mapping:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf
  i386: i386
  ppc64le: ppc64le

mimir_server:
  http_listen_port: "{{ mimir_http_listen_port }}"
  http_listen_address: "{{ mimir_http_listen_address }}"

mimir_ruler:
  rule_path: "{{ mimir_working_path }}/ruler"
  alertmanager_url: "http://localhost:{{ mimir_http_listen_port }}/alertmanager"

mimir_alertmanager:
  data_dir: "{{ mimir_working_path }}/alertmanager"
  external_url: "http://localhost:{{ mimir_http_listen_port }}/alertmanager"

