---
dependencies: []

galaxy_info:
  role_name: grafana_agent
  author: Ishan Jain
  description: Ansible Role to deploy Grafana Agent on Linux hosts.
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.11"
  platforms:
    - name: Fedora
      versions:
        - "all"
    - name: Debian
      versions:
        - "all"
    - name: Ubuntu
      versions:
        - "all"
    - name: EL
      versions:
        - "all"
  galaxy_tags:
    - grafana
    - observability