---
- name: "Restart grafana"
  ansible.builtin.service:
    name: grafana-server
    state: restarted
  become: true
  listen: "restart_grafana"
  tags:
    - grafana_run

- name: "Set privileges on provisioned dashboards"
  ansible.builtin.file:
    path: "{{ grafana_ini.paths.data }}/dashboards"
    recurse: true
    owner: "grafana"
    group: "grafana"
    mode: "u=rwX,g=rX,o=rX"
  become: true
  listen: "provisioned dashboards changed"

- name: "Set privileges on provisioned dashboards directory"
  ansible.builtin.file:
    path: "{{ grafana_ini.paths.data }}/dashboards"
    state: "directory"
    recurse: false
    mode: "0755"
  become: true
  listen: "provisioned dashboards changed"

- name: "Find dashboards subdirectories"
  ansible.builtin.find:
    paths:  "{{ grafana_ini.paths.data }}/dashboards"
    recurse: yes
    file_type: directory
  register: __dashboards_subdirs
  become: true
  listen: "provisioned dashboards changed"

- name: "Set privileges on provisioned dashboards sub-directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    recurse: false
    mode: "0755"
  with_items:
    - "{{ __dashboards_subdirs.files | map(attribute='path') | list }}"
  become: true
  listen: "provisioned dashboards changed"
