name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'
env:
  NAMESPACE: grafana
  COLLECTION_NAME: grafana

jobs:

  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    strategy:
      matrix:
        ansible:
          - stable-2.10
          - stable-2.11
          - stable-2.12
          - devel
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color --coverage
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Generate coverage report
        run: ansible-test coverage xml -v --requirements --group-by command --group-by version
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      # See the reports at https://codecov.io/gh/GITHUBORG/REPONAME
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

# ###
# # Unit tests (OPTIONAL)
# #
# # https://docs.ansible.com/ansible/latest/dev_guide/testing_units.html

#   units:
#     runs-on: ubuntu-latest
#     name: Units (Ⓐ${{ matrix.ansible }})
#     strategy:
#       # As soon as the first unit test fails, cancel the others to free up the CI queue
#       fail-fast: true
#       matrix:
#         ansible:
#           # - stable-2.9 # Only if your collection supports Ansible 2.9
#           - stable-2.10
#           - stable-2.11
#           - stable-2.12
#           - devel

#     steps:
#       - name: Check out code
#         uses: actions/checkout@v3
#         with:
#           path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#       - name: Set up Python
#         uses: actions/setup-python@v3
#         with:
#           # it is just required to run that once as "ansible-test units" in the docker image
#           # will run on all python versions it supports.
#           python-version: '3.10'

#       - name: Install ansible-base (${{ matrix.ansible }})
#         run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

#       # OPTIONAL If your unit test requires Python libraries from other collections
#       # Install them like this
#       - name: Install collection dependencies
#         run: ansible-galaxy collection install ansible.netcommon ansible.utils -p .

#       # Run the unit tests
#       - name: Run unit test
#         run: ansible-test units -v --color --docker --coverage
#         working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#       # ansible-test support producing code coverage date
#       - name: Generate coverage report
#         run: ansible-test coverage xml -v --requirements --group-by command --group-by version
#         working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#       # See the reports at https://codecov.io/gh/GITHUBORG/REPONAME
#       - uses: codecov/codecov-action@v3
#         with:
#           fail_ci_if_error: false

# ###
# # Integration tests (RECOMMENDED)
# #
# # https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html


# # If the application you are testing is available as a docker container and you want to test
# # multiple versions see the following for an example:
# # https://github.com/ansible-collections/community.zabbix/tree/master/.github/workflows

#   integration:
#     runs-on: ubuntu-latest
#     name: I (Ⓐ${{ matrix.ansible }}+py${{ matrix.python }})
#     strategy:
#       fail-fast: false
#       matrix:
#         ansible:
#           # - stable-2.9 # Only if your collection supports Ansible 2.9
#           - stable-2.10
#           - stable-2.11
#           - stable-2.12
#           - devel
#         python:
#           - '2.6'
#           - '2.7'
#           - '3.5'
#           - '3.6'
#           - '3.7'
#           - '3.8'
#           - '3.9'
#           - '3.10'
#         exclude:
#           # Because ansible-test doesn't support Python 3.9 for Ansible 2.9
#           # and Python 3.10 is supported in 2.12 or later.
#           - ansible: stable-2.9
#             python: '3.9'
#           - ansible: stable-2.9
#             python: '3.10'
#           - ansible: stable-2.10
#             python: '3.10'
#           - ansible: stable-2.11
#             python: '3.10'
            

#     steps:
#       - name: Check out code
#         uses: actions/checkout@v3
#         with:
#           path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#       - name: Set up Python
#         uses: actions/setup-python@v3
#         with:
#           # it is just required to run that once as "ansible-test integration" in the docker image
#           # will run on all python versions it supports.
#           python-version: '3.10'

#       - name: Install ansible-base (${{ matrix.ansible }})
#         run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

#       # OPTIONAL If your integration test requires Python libraries or modules from other collections
#       # Install them like this
#       - name: Install collection dependencies
#         run: ansible-galaxy collection install ansible.netcommon -p .

#       # Run the integration tests
#       - name: Run integration test
#         run: ansible-test integration -v --color --retry-on-error --continue-on-error --diff --python ${{ matrix.python }} --docker --coverage
#         working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#       # ansible-test support producing code coverage date
#       - name: Generate coverage report
#         run: ansible-test coverage xml -v --requirements --group-by command --group-by version
#         working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

#       # See the reports at https://codecov.io/gh/GITHUBORG/REPONAME
#       - uses: codecov/codecov-action@v3
#         with:
#           fail_ci_if_error: false
